package com.github.wangfeng.springboot.mybatis.datasource.mapper.db1;

import com.github.wangfeng.springboot.mybatis.datasource.entity.db1.PersonDO;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("db1PersonMapper")
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Sep 23 11:24:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Sep 23 11:24:17 CST 2019
     */
    int insert(PersonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Sep 23 11:24:17 CST 2019
     */
    int insertSelective(PersonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Sep 23 11:24:17 CST 2019
     */
    PersonDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Sep 23 11:24:17 CST 2019
     */
    int updateByPrimaryKeySelective(PersonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Mon Sep 23 11:24:17 CST 2019
     */
    int updateByPrimaryKey(PersonDO record);
}