spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        hikari:
            auto-commit: true
            connection-test-query: SELECT 1
            connection-timeout: 30000
            idle-timeout: 180000
            max-lifetime: 1800000
            maximum-pool-size: 10
            minimum-idle: 5
            pool-name: MyHikariCP
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/db1?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: root
