package com.github.wangfeng.springboot.mybatis.datasource.entity.db2;

import lombok.Data;

@Data
public class PersonDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbg.generated Mon Sep 23 11:24:17 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.user_name
     *
     * @mbg.generated Mon Sep 23 11:24:17 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.age
     *
     * @mbg.generated Mon Sep 23 11:24:17 CST 2019
     */
    private Integer age;


}